<?xml version="1.0" encoding="UTF-8"?><testrun duration="6351" footerText="Generated by PyCharm on 24.05.2020, 20:23" name="Unittests in unittest_CheckUsers.py">
    <count name="total" value="3"/>
    <count name="passed" value="3"/>
    <config nameIsGenerated="true" configId="tests" name="Unittests in unittest_CheckUsers.py">
        <module name="trpo"/>
        <option name="INTERPRETER_OPTIONS" value=""/>
        <option name="PARENT_ENVS" value="true"/>
        <option name="SDK_HOME" value=""/>
        <option name="WORKING_DIRECTORY" value="D:/trpo"/>
        <option name="IS_MODULE_SDK" value="true"/>
        <option name="ADD_CONTENT_ROOTS" value="true"/>
        <option name="ADD_SOURCE_ROOTS" value="true"/>
        <option name="_new_additionalArguments" value="&quot;&quot;"/>
        <option name="_new_target" value="&quot;D:/trpo/unittest_CheckUsers.py&quot;"/>
        <option name="_new_targetType" value="&quot;PATH&quot;"/>
    </config>
    <suite duration="6351" locationUrl="python&lt;D:\trpo&gt;://unittest_CheckUsers" name="unittest_CheckUsers" status="passed">
        <suite duration="6351" locationUrl="python&lt;D:\trpo&gt;://unittest_CheckUsers.MyTestCase" name="MyTestCase" status="passed">
            <test duration="4277" locationUrl="python&lt;D:\trpo&gt;://unittest_CheckUsers.MyTestCase.test_S_6_t1" name="test_S_6_t1 (Данные о пользователе содержатся в таблице регистрации)" status="passed">
                <output type="stderr">C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\googleapiclient\discovery.py:405: ResourceWarning: unclosed &amp;lt;ssl.SSLSocket fd=484, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=(&amp;#39;192.168.0.106&amp;#39;, 59739), raddr=(&amp;#39;64.233.164.95&amp;#39;, 443)&amp;gt;
  model = JsonModel(&amp;quot;dataWrapper&amp;quot; in features)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\googleapiclient\discovery.py:405: ResourceWarning: unclosed &amp;lt;ssl.SSLSocket fd=596, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=(&amp;#39;192.168.0.106&amp;#39;, 59740), raddr=(&amp;#39;64.233.164.95&amp;#39;, 443)&amp;gt;
  model = JsonModel(&amp;quot;dataWrapper&amp;quot; in features)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\googleapiclient\discovery.py:405: ResourceWarning: unclosed &amp;lt;ssl.SSLSocket fd=392, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=(&amp;#39;192.168.0.106&amp;#39;, 59741), raddr=(&amp;#39;64.233.165.95&amp;#39;, 443)&amp;gt;
  model = JsonModel(&amp;quot;dataWrapper&amp;quot; in features)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
</output>
            </test>
            <test duration="2073" locationUrl="python&lt;D:\trpo&gt;://unittest_CheckUsers.MyTestCase.test_S_6_t2" name="test_S_6_t2 (Данные о пользователе отсутствуют в таблице регистрации)" status="passed">
                <output type="stderr">Ran 3 tests in 6.353s
OK
</output>
            </test>
            <test duration="1" locationUrl="python&lt;D:\trpo&gt;://unittest_CheckUsers.MyTestCase.test_S_6_t3" name="test_S_6_t3 (Данные не изменяются в результате выполнения функции)" status="passed"/>
        </suite>
    </suite>
</testrun>
